# Generated by Django 5.1.5 on 2025-02-05 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_movie_movie_rdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_trailer',
            field=models.URLField(default='null', max_length=300),
        ),
        migrations.AlterField(
            model_name='shows',
            name='price',
            field=models.PositiveIntegerField(),
        ),
    ]
