# Generated by Django 5.1.5 on 2025-02-05 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_bookings_id_alter_movie_movie_trailer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_trailer',
            field=models.CharField(default='null', max_length=300),
        ),
        migrations.AlterField(
            model_name='shows',
            name='price',
            field=models.IntegerField(),
        ),
    ]
